version: '3'

services:
  app:
    build:
      context: .
    command: bash -c 'rm tmp/pids/server.pid 2>/dev/null; bin/rails s -b "0.0.0.0"'
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'

volumes:
  bundle:
